FROM openjdk:17-jdk-alpine
WORKDIR /app

# Copy the JAR from the Jenkins workspace
COPY backend/target/student-registration-backend-0.0.1-SNAPSHOT.jar app.jar

# Update the exposed port to 8081
EXPOSE 8081

# Ensure the Java app itself is told to run on 8081
ENTRYPOINT ["java", "-jar", "app.jar", "--server.port=8081"]
